name: deploy
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3
      - name: run-build
        env:
          REACT_APP_API_KEY: '${{ secrets.REACT_APP_API_KEY }}'
          REACT_APP_AUTH_DOMAIN: '${{ secrets.REACT_APP_AUTH_DOMAIN }}'
          REACT_APP_PROJECT_ID: '${{ secrets.REACT_APP_PROJECT_ID }}'
          REACT_APP_STORAGE_BUCKET: '${{ secrets.REACT_APP_STORAGE_BUCKET }}'
          REACT_APP_MESSAGING_SENDER_ID: '${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}'
          REACT_APP_APP_ID: '${{ secrets.REACT_APP_APP_ID }}'
        run: |
          npm ci
          npm run build
      - name: run-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINI_PAINT_INN23 }}'
          channelId: live
          projectId: mini-paint-inn23
